### PR TITLE
get headings straight

### PR DESCRIPTION
**Pull request by sappelhoff**
inserting whitespace to have correct markdown rendering

### CODE REVIEW

**Comment by sappelhoff** [comment]
Hi @VisLab, off on a vacation? :-)

**Comment by sappelhoff** [comment]
@jcockfie

**Comment by VisLab** [comment]
Stefan,
I was copied on a github email about EEG-HDF5-Tools from you. I see you
have a pull request but don't see anything else.   Jcockfie, who was the
senior staff research software developer left in September. He was
maintaining that repo.  You will need to walk me through what happened on
this and if you want to merge something, I am willing to work on it, but I
need to understand the context and the issue as I haven't worked on this
code at all.

Thanks,
Kay

**Comment by sappelhoff** [comment]
Ah I see. Hi Kay,

my pull request is unrelated to the code and only refers to the markdown formatting of the README file. Specifically, headings will be formatted as headings only if there is a whitespace between the `#` sign and the text.

Examples:

- `# This is a valid first-level heading`
- `## This is a valid second-level heading`
- `#This is an invalid heading` (see the missing whitespace)

I am inserting these whitespaces in your README, so that it is rendered correctly and becomes more readable for users.

**Pull request merged**
